sudo: required
services: 
    - docker
    
before_install:
    - docker build -t nmartynov/docker-kubernetes-course -f Dockerfile.dev .
    
script:
    - docker run -e CI=true nmartynov/docker-kubernetes-course npm run test
    
deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'docker-react-app-linux'
    env: 'DockerReactAppLinux-env'
    bucket_name: 'elasticbeanstalk-us-east-2-234120039325'
    bucket_path: 'docker-react-app-linux'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY